export default function KeysData() {
  return [
    [
      {
        type: 'digits',
        content: [
          '~/`',
          '1/!',
          '2/@',
          '3/#',
          '4/$',
          '5/%',
          '6/:',
          '7/?',
          '8/*',
          '9/(',
          '0/)',
          '-/_',
          '=/+',
        ],
      },
      { type: 'complex', content: 'Backspace', id: 'key-backspace' },
    ],
    [
      { type: 'complex', content: 'Tab', id: 'key-tab' },
      {
        type: 'letters',
        content: [
          'q/й',
          'w/ц',
          'e/у',
          'r/к',
          't/е',
          'y/н',
          'u/г',
          'i/ш',
          'o/щ',
          'p/з',
          '[/х',
          ']/ъ',
          '\\//',
        ],
      },
      { type: 'complex', content: 'DEL', id: 'key-del' },
    ],
    [
      { type: 'complex', content: 'CapsLock', id: 'key-caps' },
      {
        type: 'letters',
        content: [
          'a/й',
          's/ц',
          'd/у',
          'f/к',
          'g/е',
          'h/н',
          'j/г',
          'k/ш',
          'l/щ',
          ';/з',
          "'/х",
        ],
      },
      { type: 'complex', content: 'Enter', id: 'key-enter' },
    ],
    [
      { type: 'complex', content: 'Shift', id: 'key-shift' },
      {
        type: 'letters',
        content: [
          'z/я',
          'x/ч',
          'c/с',
          'v/м',
          'b/и',
          'n/т',
          'm/ь',
          './б',
          ',/ю',
          '//.',
        ],
      },
      { type: 'complex', content: '', id: 'key-arrow-up' },
      { type: 'complex', content: 'Shift', id: 'key-shift' },
    ],
    [
      { type: 'complex', content: 'Ctrl', id: 'key-ctrl' },
      { type: 'complex', content: 'Win', id: 'key-win' },
      { type: 'complex', content: 'Alt', id: 'key-alt' },
      { type: 'complex', content: '', id: 'key-space' },
      { type: 'complex', content: 'Alt', id: 'key-alt' },
      { type: 'complex', content: 'Ctrl', id: 'key-ctrl' },
      { type: 'complex', content: '', id: 'key-arrow-down' },
      { type: 'complex', content: '', id: 'key-arrow-left' },
      { type: 'complex', content: '', id: 'key-arrow-right' },
    ],
  ];
}
