/* eslint-disable */
// prettier-ignore
/*
 * 	В данном файле содержатся сырые данные, для их лучшего отображения и избегания прокидывания ESlint-ом
 *	ошибок, я решил экранировать его от проверок
 */
export default function KeysData() {
  return [
    [
      { en: '`',  shift: '~', id: 'Backquote', ru: 'ё', classes: 'letter-key'},
      { en: '1', shift: '!', id: 'Digit1', classes: 'digit' },
      { en: '2', shift: '@', id: 'Digit2', classes: 'digit' },
      { en: '3', shift: '#', id: 'Digit3', classes: 'digit' },
      { en: '4', shift: '$', id: 'Digit4', classes: 'digit' },
      { en: '5', shift: '%', id: 'Digit5', classes: 'digit' },
      { en: '6', shift: ':', id: 'Digit6', classes: 'digit' },
      { en: '7', shift: '?', id: 'Digit7', classes: 'digit' },
      { en: '8', shift: '*', id: 'Digit8', classes: 'digit' },
      { en: '9', shift: '(', id: 'Digit9', classes: 'digit' },
      { en: '0', shift: ')', id: 'Digit0', classes: 'digit' },
      { en: '-', shift: '_', id: 'Minus', classes: 'digit' },
      { en: '=', shift: '+', id: 'Equal', classes: 'digit' },
      { en: 'Backspace', id: 'Backspace', classes: 'key-backspace' },
    ],
    [
      { en: 'Tab', id: 'Tab', classes: 'key-tab' },
      { en: 'q', ru: 'й', id: 'KeyQ', classes: 'letter-key' },
      { en: 'w', ru: 'ц', id: 'KeyW', classes: 'letter-key' },
      { en: 'e', ru: 'у', id: 'KeyE', classes: 'letter-key' },
      { en: 'r', ru: 'к', id: 'KeyR', classes: 'letter-key' },
      { en: 't', ru: 'е', id: 'KeyT', classes: 'letter-key' },
      { en: 'y', ru: 'н', id: 'KeyY', classes: 'letter-key' },
      { en: 'u', ru: 'г', id: 'KeyU', classes: 'letter-key' },
      { en: 'i', ru: 'ш', id: 'KeyI', classes: 'letter-key' },
      { en: 'o', ru: 'щ', id: 'KeyO', classes: 'letter-key' },
      { en: 'p', ru: 'з', id: 'KeyP', classes: 'letter-key' },
      { en: '[', shift: '{', ru: 'х', id: 'BracketLeft', classes: 'letter-key'},
      { en: ']', shift: '}', ru: 'ъ', id: 'BracketRight', classes: 'letter-key'},
      { en: '\\', ru: '/', id: 'Backslash', classes: 'letter-key' },
      { en: 'DEL', id: 'Delete', classes: 'key-del' },
    ],
    [
      { en: 'Caps Lock', id: 'CapsLock', classes: 'key-caps' },
      { en: 'a', ru: 'ф', id: 'KeyA', classes: 'letter-key' },
      { en: 's', ru: 'ы', id: 'KeyS', classes: 'letter-key' },
      { en: 'd', ru: 'в', id: 'KeyD', classes: 'letter-key' },
      { en: 'f', ru: 'а', id: 'KeyF', classes: 'letter-key' },
      { en: 'g', ru: 'п', id: 'KeyG', classes: 'letter-key' },
      { en: 'h', ru: 'р', id: 'KeyH', classes: 'letter-key' },
      { en: 'j', ru: 'о', id: 'KeyJ', classes: 'letter-key' },
      { en: 'k', ru: 'л', id: 'KeyK', classes: 'letter-key' },
      { en: 'l', ru: 'д', id: 'KeyL', classes: 'letter-key' },
      { en: ';', ru: 'ж', id: 'Semicolon', classes: 'letter-key' },
      { en: "'", ru: 'э', id: 'Quote', classes: 'letter-key' },
      { en: 'Enter', id: 'Enter', classes: 'key-enter' },
    ],
    [
      { en: 'Shift', id: 'ShiftLeft', classes: 'key-shift' },
      { en: 'z', ru: 'я', id: 'KeyZ', classes: 'letter-key' },
      { en: 'x', ru: 'ч', id: 'KeyX', classes: 'letter-key' },
      { en: 'c', ru: 'с', id: 'KeyC', classes: 'letter-key' },
      { en: 'v', ru: 'м', id: 'KeyV', classes: 'letter-key' },
      { en: 'b', ru: 'и', id: 'KeyB', classes: 'letter-key' },
      { en: 'n', ru: 'т', id: 'KeyN', classes: 'letter-key' },
      { en: 'm', ru: 'ь', id: 'KeyM', classes: 'letter-key' },
      { en: ',', ru: 'ю', id: 'Comma', classes: 'letter-key' },
      { en: '.', ru: 'б', id: 'Period', classes: 'letter-key' },
      { en: '/', ru: '.', id: 'Slash', classes: 'letter-key' },
      { en: '↑', id: 'ArrowUp', classes: 'key-arrow-up' },
      { en: 'Shift', id: 'ShiftRight', classes: 'key-shift' },
    ],
    [
      { en: 'Ctrl', id: 'ControlLeft', classes: 'key-ctrl' },
      { en: 'Win', id: 'MetaLeft', classes: 'key-win' },
      { en: 'Alt', id: 'AltLeft', classes: 'key-alt' },
      { en: '', id: 'Space', classes: 'key-space' },
      { en: 'Alt', id: 'AltRight', classes: 'key-alt' },
      { en: 'Ctrl', id: 'ControlRight', classes: 'key-ctrl' },
      { en: '←', id: 'ArrowLeft', classes: 'key-arrow-left' },
      { en: '↓', id: 'ArrowDown', classes: 'key-arrow-down' },
      { en: '→', id: 'ArrowRight', classes: 'key-arrow-right' },
    ],
  ];
}
/* eslint-disable */
